//
//  MainPresenter.swift
//  Names_Of_NewYork
//
//  Created by Yasir Ali on 11/01/2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
    func presentLoadedBabyNamesInfo(response: Main.LoadBabyNamesInfo.Response)
    func presentPopularBabyNameInfo(response: Main.PopularBabyName.Response)
}

class MainPresenter: MainPresentationLogic
{
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentLoadedBabyNamesInfo(response: Main.LoadBabyNamesInfo.Response)
    {
        let viewModel = Main.LoadBabyNamesInfo.ViewModel(babyNamesInfo: response.babyNamesInfo, error: response.error)
        viewController?.displayLoadedBabyNamesInfo(viewModel: viewModel)
    }
    
    func presentPopularBabyNameInfo(response: Main.PopularBabyName.Response) {
        let viewModel = Main.PopularBabyName.ViewModel(babyNameInfo: response.babyNameInfo, error: response.error)
        viewController?.displayPopularBabyNameInfo(viewModel: viewModel)
    }
}
