//
//  MainWorker.swift
//  Names_Of_NewYork
//
//  Created by Yasir Ali on 11/01/2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker {
    typealias LoadBabyNameInfoCompletion = ([BabyNameInfo]?, AppError?) -> ()
    func loadBabyNameInfo(completion: @escaping LoadBabyNameInfoCompletion) {
        if let fileURL = Bundle.main.url(forResource: "baby_names_info", withExtension: "json") {
            do {
                let data = try Data(contentsOf: fileURL)
                let decoder = JSONDecoder()
                let babyNamesArray = try decoder.decode([[String]].self, from: data)
                var babyNames: [BabyNameInfo] = []
                for info in babyNamesArray {
                    let babyName = BabyNameInfo(babyNameInfo: info)
                    babyNames.append(babyName)
                }
                completion(babyNames, nil)

            } catch {
                completion(nil, AppError(description: error.localizedDescription))
            }
        } else {
            completion(nil, AppError(description: "JSON file not found"))
        }
    }
    
    typealias PopularBabyNameInfoCompletion = (BabyNameInfo?, AppError?) -> ()
    func getPopularBabyNameInfo(gender: String, from babyNamesInfo: [BabyNameInfo], completion: @escaping PopularBabyNameInfoCompletion) {
        guard !babyNamesInfo.isEmpty else {
            completion(nil, AppError(description: "Unable to find baby name."))
            return
        }
        
        let babyNamesByGender = babyNamesInfo.filter { $0.gender.lowercased() == gender.lowercased()}
        let sortedBabyNamesByNoOfBabies = babyNamesByGender.sorted { $0.numberOfBabies > $1.numberOfBabies }
        let randomIndex = Int(arc4random_uniform(UInt32(sortedBabyNamesByNoOfBabies.count)))
        
        completion(sortedBabyNamesByNoOfBabies[randomIndex], nil)
    }
}
