//
//  MainModels.swift
//  Names_Of_NewYork
//
//  Created by Yasir Ali on 11/01/2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main
{
    // MARK: Use cases
    
    enum LoadBabyNamesInfo
    {
        struct Request
        {
        }
        struct Response
        {
            var babyNamesInfo: [BabyNameInfo]?
            var error: AppError?
        }
        struct ViewModel
        {
            var babyNamesInfo: [BabyNameInfo]?
            var error: AppError?
        }
    }
    
    enum PopularBabyName
    {
        struct Request
        {
            var gender: String
            var babyNamesInfo: [BabyNameInfo]
        }
        struct Response
        {
            var babyNameInfo: BabyNameInfo?
            var error: AppError?
        }
        struct ViewModel
        {
            var babyNameInfo: BabyNameInfo?
            var error: AppError?
        }
    }
}
