//
//  MainInteractor.swift
//  Names_Of_NewYork
//
//  Created by Yasir Ali on 11/01/2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
    func loadBabyNameInfo(request: Main.LoadBabyNamesInfo.Request)
    func loadBabyNameInfoFromApi(request: Main.LoadBabyNamesInfoFromApi.Request)
    func getPopularBabyNameInfo(request: Main.PopularBabyName.Request)
}

protocol MainDataStore
{
    //var name: String { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{
    var presenter: MainPresentationLogic?
    var worker = MainWorker()
    //var name: String = ""
    
    // MARK: Do something
    
    func loadBabyNameInfo(request: Main.LoadBabyNamesInfo.Request) {
        worker.loadBabyNameInfo { [weak self] babyNamesInfo, error in
            let response = Main.LoadBabyNamesInfo.Response(babyNamesInfo: babyNamesInfo, error: error)
            self?.presenter?.presentLoadedBabyNamesInfo(response: response)
        }
    }
    
    func loadBabyNameInfoFromApi(request: Main.LoadBabyNamesInfoFromApi.Request) {
        worker.loadBabyNameInfoFromApi { [weak self] babyNamesInfo, error in
            let response = Main.LoadBabyNamesInfoFromApi.Response(babyNamesInfo: babyNamesInfo, error: error)
            self?.presenter?.presentLoadedBabyNamesInfoFromApi(response: response)
        }
    }
    
    func getPopularBabyNameInfo(request: Main.PopularBabyName.Request) {
        worker.getPopularBabyNameInfo(gender: request.gender, ethnicity: request.ethnicity, from: request.babyNamesInfo) { [weak self] babyNameInfo, error in
            let response = Main.PopularBabyName.Response(babyNameInfo: babyNameInfo, error: error)
            self?.presenter?.presentPopularBabyNameInfo(response: response)
        }
    }
}
